version: '3.8'
services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy_network

  upstream_server1:
    image: nginx
    volumes:
      - ./upstream_server.conf:/etc/nginx/nginx.conf      
      - ./index-1.html:/etc/nginx/html/upstream_server/index.html 
    networks:
      - proxy_network

  upstream_server2:
    image: nginx
    volumes:
      - ./upstream_server.conf:/etc/nginx/nginx.conf      
      - ./index-2.html:/etc/nginx/html/upstream_server/index.html        
    networks:
      - proxy_network

networks:
  proxy_network:
